#+title: Tomato Productivity Timer for the i3 window manager
#+author: Thomas Rometsch

A productivity timer for [[https://github.com/i3/i3status][i3status]] following the [[https://en.wikipedia.org/wiki/Pomodoro_Technique][promodoro tactic]].

* Session

In this piece of software, a session consists of one focus period (25min) and one break (5min).
After 3 successful sessions, the fourth break is longer (20min)

* Status String

The status string is build up by 3 or 4 elements.
Its general syntax

#+BEGIN_EXAMPLE
number stage [paused] minutes:seconds
#+END_EXAMPLE

where the =paused= part is only displayed when the session is paused and =number= indicates the number of the session in a row of 4 sessions.

The stages of the session are indicated with the following symbols:
| focus   | ∞  | infinity |
| break   | ☕ | hot beverage |
| paused  | †  | dagger |

An example for the 2nd session in =break= stage with 3:25 remaining is

#+BEGIN_EXAMPLE
2 ☕ 3:25
#+END_EXAMPLE

* Controls

There are three things you can do as a user.

1. start a focus / break period
2. pause / resume
3. stop

=tomatotimer= automatically takes care of choosing the correct next stage (focus/break) and the length (short/long break).

These actions should be bind to keyboard shortcuts.
Since this is supposed to be used with the =i3= window manager, the appropriate lines in the config file are

#+BEGIN_EXAMPLE
bindsym $mod+Control+p exec "~/repo/i3tomato/tomatotimer.py pause"
bindsym $mod+Control+t exec "~/repo/i3tomato/tomatotimer.py start"
#+END_EXAMPLE


* i3status element

You can display the status of the tomatotimer in the i3status bar by using the provided =wrapper.py= script.

My =i3= config entry for this looks like

#+BEGIN_EXAMPLE
bar {
        status_command i3status | ~/repo/i3tomato/wrapper.py
}
#+END_EXAMPLE

It might be nice to set the refresh interval of =i3status= to 1 second in the general block.

#+BEGIN_EXAMPLE
general {
        ...
        interval = 1
        ...
}
#+END_EXAMPLE

* Run File

Information about the current session is stored in =/run/user/your_uid/tomatotimer=.
The file contains in the respective line:

1. stage (focus/break)
2. status (running/paused) in the second line, the
3. number of the session sessions done before in a row without a long break
4. stop time as an ISO timestamp (YYYY-MM-DD HH:MM:SS)
5. remaining time in seconds used for pausing/resuming

If the session is paused, the stop time is replaced with the time remaining, which is then used to calculate a new stop time when resuming.

* TODO Log File

You can use =i3tomato= as a rudimentary time tracker app.

The file you want the log to be written at must be specified as an *absolute* path at the beginning of the script by setting the variable =logfile=.
